import { Slider } from "@/components/ui/slider"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { ResponsiveLine } from "@nivo/line"

export function Graphs() {
  return (
    <div className="flex flex-col gap-4 p-4 md:gap-8 md:p-6 bg-spaceship-scifi max-w-[600px] mx-auto my-10">
      <div className="mx-auto w-full">
        <div className="grid gap-4">
          <div className="flex flex-col gap-4">
            <p className="font-serif text-[27px]">Scaling Laws</p>
            <p className="font-sans text-[14px]"> Net Sales represent the total amount of sales revenue generated by a business after deducting the costs
              associated with producing and selling its goods or services.</p>
              <Button>Sign up to &#8594;</Button>
          </div>
          <div className="grid gap-5 py-5">
            <div className="grid gap-4">
              <h2 className="font-serif text-[23px]">Net Sales</h2>
              <div className="flex items-center gap-4">
                <Slider className="w-full">
                  <div className="h-2.5">
                    <div />
                  </div>
                  <div />
                </Slider>
                <Input className="w-12" defaultValue={25} placeholder="0" type="number" />
                <Button size="none">Update</Button>
              </div>
            </div>
            <CurvedlineChart className="w-full aspect-[2/1]" />
            <p className="font-sans">
              Net Sales represent the total amount of sales revenue generated by a business after deducting the costs
              associated with producing and selling its goods or services.
            </p>
          </div>
          <div className="grid gap-4">
            <div className="grid gap-1">
              <h2 className="font-semibold text-lg">Gross Profit</h2>
              <div className="flex items-center gap-4">
                <Slider className="w-full">
                  <div className="h-2.5">
                    <div />
                  </div>
                  <div />
                </Slider>
                <Input className="w-12" defaultValue={50} placeholder="0" type="number" />
                <Button size="sm">Update</Button>
              </div>
            </div>
            <CurvedlineChart className="w-full aspect-[2/1]" />
          </div>
          <div className="grid gap-4">
            <div className="grid gap-1">
              <h2 className="font-semibold text-lg">Gross Margin</h2>
              <div className="flex items-center gap-4">
                <Slider className="w-full">
                  <div className="h-2.5">
                    <div />
                  </div>
                  <div />
                </Slider>
                <Input className="w-12" defaultValue={75} placeholder="0" type="number" />
                <Button size="sm">Update</Button>
              </div>
            </div>
            <CurvedlineChart className="w-full aspect-[2/1]" />
          </div>
        </div>
      </div>
    </div>
  );
}


function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>
  );
}
